import htmlmin from 'html-minifier-terser';

const isProduction = process.env.ELEVENTY_ENV === 'production';
const rawPathPrefix = process.env.ELEVENTY_PATHPREFIX || '';
const pathPrefix =
  rawPathPrefix && rawPathPrefix !== '/' ? rawPathPrefix.replace(/\/$/, '') : '';

const prefixRootRelativeUrls = content => {
  if (!pathPrefix) {
    return content;
  }

  return content
    .replaceAll(`="${pathPrefix}/`, '="__PATH_PREFIX__/')
    .replaceAll(`='${pathPrefix}/`, "='__PATH_PREFIX__/")
    .replaceAll(`url(${pathPrefix}/`, 'url(__PATH_PREFIX__/')
    .replaceAll(`url("${pathPrefix}/`, 'url("__PATH_PREFIX__/')
    .replaceAll(`url('${pathPrefix}/`, "url('__PATH_PREFIX__/")
    .replace(/=(["'])\/(?!\/)/g, `=$1${pathPrefix}/`)
    .replace(/,\s*\/(?!\/)/g, `, ${pathPrefix}/`)
    .replace(/url\((["']?)\/(?!\/)/g, `url($1${pathPrefix}/`)
    .replaceAll('__PATH_PREFIX__/', `${pathPrefix}/`);
};

export const htmlConfig = eleventyConfig => {
  eleventyConfig.addTransform('html-minify', (content, outputPath) => {
    if (outputPath && outputPath.endsWith('.html')) {
      const prefixedContent = prefixRootRelativeUrls(content);

      if (isProduction) {
        return htmlmin.minify(prefixedContent, {
          collapseBooleanAttributes: true,
          collapseWhitespace: true,
          decodeEntities: true,
          includeAutoGeneratedTags: false,
          removeComments: true
        });
      }

      return prefixedContent;
    }

    return content;
  });
};
